name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: read-all
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()           # run this step even if previous step failed
      with:
        name: Spec Flow Tests              # Name of the check run which will be created
        path: 'TestResults/net6.0/*.trx'  # Path to test results
        reporter: dotnet-trx               # Format of test results
